### ISSUE TITLE
dungeons, mission data not processed

### ISSUE THREAD

**Issue by winter0729** [pyfa-org/Phobos#14]
eve-21.05.2291839

  processing dungeons
    unable to fetch data - IOError: Unexpected cFSD schema version. Loader schema: (5508473695024844245, 6829693746456926295) Header schema field: (631582858141601371, 3392568259313855816)

  processing missions
    unable to fetch data - IOError: Unexpected cFSD schema version. Loader schema: (7061632699330772098, 11478092164589306168) Header schema field: (17443728786762165585, 12624431704568200047)

**Comment by winter0729** [comment]
processing atoms
    unable to fetch data - SystemError: Negative size passed to PyString_FromStringAndSize

**Comment by DarkFenX** [comment]
```
  processing atoms
...
  processing dungeons
    field description: 392 entries, 3528 translations
    field dungeonName: 5039 entries, 45243 translations
    field gameplayDescription: 21 entries, 189 translations
...
  processing missions
    field name: 2816 entries, 25344 translations
```

Works fine for me, both single- and multi-language mode. I had some issues with phobos as well, but it turned out that some EVE files were corrupt or still were being downloaded. Make sure you have correct data in place.

It's also hard to debug, since phobos executes 3rd party code. I don't know what it does, and I don't know how exactly loaders work. So I don't think I will be able to support you here.

**Comment by winter0729** [comment]
After running an integrity check on an older version of Runcheon, it was resolved. Thank you.
